name: "Run deptry"
description: "Setup Python environment and run deptry . to check for dependency issues"
inputs:
  options:
    description: "Additional options for deptry command"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Setup standard environment
      uses: Somerandomguy10111/devops/actions/basepy@main

    - name: Install devops
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/Somerandomguy10111/devops
      shell: bash

    - name: Run deptry tests
      run: |
        mapdeptry . --pep621-dev-dependency-groups=test ${{ inputs.options }}
      shell: bash
