name: Publish Python distribution to PyPI

on:
  release:
    types: [created]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: Somerandomguy10111/devops/actions/basepy@main
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    - name: Build and publish
      run: |
        python -m build
        twine upload -u root -p '' --repository-url http://51.20.104.167:5000/root/dev/ dist/*

#        twine upload dist/* --repository pypi
#      env:
#        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
#twine upload -u root -p '' --repository-url http://51.20.104.167:5000/root/dev/ dist/*