name: Workflows

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  ToxTests:
    runs-on: ubuntu-latest
    steps:
      - uses: Somerandomguy10111/devops/actions/basepy@main
      - uses: Somerandomguy10111/devops/actions/toxtests@main
  Dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: Somerandomguy10111/devops/actions/basepy@main
      - uses: Somerandomguy10111/devops/actions/deptry@main
  ChromeInstall:
    runs-on: ubuntu-latest
    steps:
      - uses: Somerandomguy10111/devops/actions/chrome@main
  XServer:
    runs-on: ubuntu-latest
    steps:
      - uses: Somerandomguy10111/devops/actions/xserver@main
  GHCreds:
    runs-on: ubuntu-latest
    steps:
      - uses: Somerandomguy10111/devops/actions/ghcreds@main
        with:
          git_user: Somerandomguy10111
          git_pass: ${{ secrets.DEV_EXAMPLE }}